### ISSUE TITLE
New Annotations?

### ISSUE THREAD

**Issue by JeremyOgo** [bozcani/auairdataset#5]
This is related to issue #3, but I just wanted to check to see if there were any updates. 

Any chance of corrected annotations being released sometime soon?

Would love to use this dataset for some new methods my team is developing, as there aren't too many top-down image detection/classification datasets out there.

**Comment by bozcani** [comment]
Hi @JeremyOgo,

We are planning to release new annotations in August. Sorry for delay.

Best,
Ilker

**Comment by JeremyOgo** [comment]
Awesome! Looking forward to it! Do you mind if I ask, how are creating/improving the new labels? Is it a manual process by your team, or will you be using a professional image annotation service? (not Amazon Mechanical Turk I assume...)

**Comment by bozcani** [comment]
It is manual work by our team, and still going on. We are using the VIA image annotator (an extended version modified by us) for our labeling process.

**Comment by bozcani** [comment]
We updated the annotations, and will continuously improve it.
