### ISSUE TITLE
annotations for yolo?

### ISSUE THREAD

**Issue by maxiaotian520** [bozcani/auairdataset#6]
Hello,
Thanks for sharing this wonderful datasets. I've read your paper and found that you also use the datasets to train yolov3-tiny. That's also the same part of the work on my research. So could you please also provide a version of annotation for yolo if you have? Appreciated!

**Comment by bozcani** [comment]
Hi @maxiaotian520 ,

Unfortunately, I don't have it in my hand at this moment. 

@pohjao has really nice fork of our dataset API. It includes a function to export YOLO annotations. Does it help you? 

Link: https://github.com/pohjao/auairdataset/blob/master/auairtools/to_yolo.py

**Comment by bozcani** [comment]
I am closing the issue because of inactivity. Feel free to re-open it, or contact me.
